### ISSUE TITLE
InvalidOperationException in dotnet 9

### ISSUE THREAD

**Issue by alexhelms** [Kir-Antipov/HotAvalonia#14]
I upgraded my app to dotnet 9 and when running in debug I now get an exception on startup.

```
   at HotAvalonia.Helpers.MethodHelper.GetFunctionPointerAddress(MethodBase method)
   at HotAvalonia.Helpers.MethodHelper.OverrideMethod(MethodBase source, MethodBase replacement, IntPtr& sourceFunctionPointer)
   at HotAvalonia.Helpers.MethodHelper.OverrideMethod(MethodBase source, MethodBase replacement)
   at HotAvalonia.Reflection.Inject.CallbackInjector.Inject(MethodBase target, MethodBase callback, Object thisArg)
   at HotAvalonia.Reflection.Inject.CallbackInjector.Inject(MethodBase target, Delegate callback)
   at HotAvalonia.AvaloniaControlManager.TrySubscribeToPopulate(AvaloniaControlInfo controlInfo, Func`3 onPopulate)
   at HotAvalonia.AvaloniaControlManager..ctor(AvaloniaControlInfo controlInfo, String fileName)
   at HotAvalonia.AvaloniaHotReloadContext.ResolveControlManager(AvaloniaControlInfo controlInfo, String rootPath)
   at HotAvalonia.AvaloniaHotReloadContext.<>c__DisplayClass3_0.<.ctor>b__0(AvaloniaControlInfo x)
   at System.Linq.Enumerable.IEnumerableSelectIterator`2.MoveNext()
   at System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at HotAvalonia.AvaloniaHotReloadContext..ctor(String rootPath, IEnumerable`1 controls)
   at HotAvalonia.AvaloniaHotReloadContext.FromAssembly(Assembly assembly, String rootPath)
   at HotAvalonia.AvaloniaHotReloadContext.FromControl(Object control, String controlPath)
   at HotAvalonia.AvaloniaHotReloadExtensions.EnableHotReload(Application app, String appFilePath) in E:\packages\nuget\hotavalonia.extensions\1.1.1\contentFiles\cs\netstandard2.1\AvaloniaHotReloadExtensions.cs:line 72
```

Disabling HotAvalonia by removing the `ENABLE_XAML_HOT_RELOAD` define lets me run the app in debug.

**Comment by AVVI94** [comment]
I encountered the same error after upgrading to .NET 9, so I tried the Mono-based implementation from the development branch, and it works fine (after updating the Mono packages to a version that supports .NET 9).

**Comment by Kir-Antipov** [comment]
That's a shame, really. I guess my cross-platform injection method is now completely broken with .NET 9. Thankfully, I anticipated this, as .NET 7 had already broken it for apps running in Release mode upon its release. Thus, the development branch already includes the option of using `MonoMod` to perform injections *(despite its name, this is a cross-framework library that supports method injections for Mono, .NET Framework, and .NET)*

I'll leave the issue open until I release these changes. Additionally, I'll try to investigate reviving my injection method, as it could be useful for cases when a new .NET version is released and `MonoMod` doesn't support it yet.

**Comment by Linlccc** [comment]
So now, if I want to use it in .NET 9, what should I do? That would be great if there are no major changes.

**Comment by Kir-Antipov** [comment]
Technically, v2.0.0 is fully ready for release. However, since it's a major update, I'd like to also address #8 before proceeding with it. Hopefully, that will be resolved within a few days.  

In the meantime, if you really-really need to make it work ASAP, you can grab an artifact built by GitHub Actions and put it into a local NuGet repository :)

**Comment by Linlccc** [comment]
I tried to update to 2.0.0 and encountered problems in .NET 8.0.

   在 HotAvalonia.Helpers.MethodHelper.GetFunctionPointerAddress(MethodBase method)
   在 HotAvalonia.Reflection.Inject.<MethodInjector>F3EEC361987EED8E921415DE63CCC2DF24DC21B33A2A80A442437A706C5A22761__BytecodeInjection..ctor(MethodBase source, MethodBase replacement)
   在 HotAvalonia.Reflection.Inject.MethodInjector.Inject(MethodBase source, MethodInfo replacement)
   在 HotAvalonia.Reflection.Inject.CallbackInjector.Inject(MethodBase target, MethodBase callback, Object thisArg)
   在 HotAvalonia.Reflection.Inject.CallbackInjector.Inject(MethodBase target, Delegate callback)
   在 HotAvalonia.AvaloniaAssetManager..ctor(IServiceProvider serviceProvider)
   在 HotAvalonia.<AvaloniaHotReloadContext>FE175869FAF7D7C5AA3B3E1E0D6C8D0FB6B623B28E34A613076134802E243266C__AvaloniaAssetsHotReloadContext..ctor(IServiceProvider serviceProvider)
   在 HotAvalonia.AvaloniaHotReloadContext.ForAssets(IServiceProvider serviceProvider)
   在 HotAvalonia.AvaloniaHotReloadContext.ForAssets()
   在 HotAvalonia.AvaloniaHotReloadExtensions.EnableHotReload(Application app, String appFilePath) 在 C:\Users\lin\.nuget\packages\hotavalonia.extensions\2.0.0\contentFiles\cs\any\AvaloniaHotReloadExtensions.cs 中: 第 113 行
   在 LCopy.App.Initialize() 在 Z:\Files\Git\Gitea\LCopy\LCopy\App.axaml.cs 中: 第 14 行
   在 Avalonia.AppBuilder.SetupUnsafe()
   在 Avalonia.AppBuilder.Setup()
   在 Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   在 Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   在 LCopy.Program.Main(String[] args) 在 Z:\Files\Git\Gitea\LCopy\LCopy\Program.cs 中: 第 11 行

**Comment by Linlccc** [comment]
In .NET 9.0, using 2.0.0 also has exceptions.
messages：The type initializer for 'HotAvalonia.Helpers.AvaloniaControlHelper' threw an exception.

   在 HotAvalonia.Helpers.AvaloniaControlHelper.TryInjectPopulateOverride(FieldInfo populateOverride, Action`2 populate, IInjection& injection)
   在 HotAvalonia.AvaloniaControlInfo.TryInjectPopulateOverride(Action`2 populate, IInjection& injection)
   在 HotAvalonia.AvaloniaControlManager.TryInjectPopulateCallback(AvaloniaControlInfo controlInfo, Func`3 onPopulate, IInjection& injection)
   在 HotAvalonia.AvaloniaControlManager..ctor(AvaloniaControlInfo controlInfo, String fileName)
   在 HotAvalonia.<AvaloniaHotReloadContext>FE175869FAF7D7C5AA3B3E1E0D6C8D0FB6B623B28E34A613076134802E243266C__AvaloniaProjectHotReloadContext.ResolveControlManager(AvaloniaControlInfo controlInfo, String rootPath)
   在 HotAvalonia.<AvaloniaHotReloadContext>FE175869FAF7D7C5AA3B3E1E0D6C8D0FB6B623B28E34A613076134802E243266C__AvaloniaProjectHotReloadContext.<>c__DisplayClass3_0.<.ctor>b__0(AvaloniaControlInfo x)
   在 System.Linq.Enumerable.ArraySelectIterator`2.MoveNext()
   在 System.Linq.Enumerable.ToDictionary[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   在 HotAvalonia.<AvaloniaHotReloadContext>FE175869FAF7D7C5AA3B3E1E0D6C8D0FB6B623B28E34A613076134802E243266C__AvaloniaProjectHotReloadContext..ctor(String rootPath, IEnumerable`1 controls)
   在 HotAvalonia.AvaloniaHotReloadContext.FromUnverifiedAssembly(Assembly assembly)
   在 HotAvalonia.AvaloniaHotReloadContext.<>c.<FromAppDomain>b__3_0(AppDomain _, Assembly asm)
   在 HotAvalonia.<IHotReloadContext>FFD67A1B8CF259EF6F4152BF5B50BCFF9B8BE44F0CF610B392C6F2E94FE204B95__AppDomainHotReloadContext.<.ctor>b__4_0(Assembly x)
   在 System.Linq.Enumerable.ArraySelectIterator`2.MoveNext()
   在 System.Linq.Enumerable.IEnumerableWhereIterator`1.MoveNext()
   在 System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()
   在 System.Linq.Enumerable.IEnumerableWhereIterator`1.ToArray()
   在 HotAvalonia.HotReloadContext.Combine(IEnumerable`1 contexts)
   在 HotAvalonia.<IHotReloadContext>FFD67A1B8CF259EF6F4152BF5B50BCFF9B8BE44F0CF610B392C6F2E94FE204B95__AppDomainHotReloadContext..ctor(AppDomain appDomain, Func`3 contextFactory)
   在 HotAvalonia.HotReloadContext.FromAppDomain(AppDomain appDomain, Func`3 contextFactory)
   在 HotAvalonia.AvaloniaHotReloadContext.FromAppDomain(AppDomain appDomain)
   在 HotAvalonia.AvaloniaHotReloadContext.FromAppDomain()
   在 HotAvalonia.AvaloniaHotReloadExtensions.EnableHotReload(Application app, String appFilePath) 在 C:\Users\lin\.nuget\packages\hotavalonia.extensions\2.0.0\contentFiles\cs\any\AvaloniaHotReloadExtensions.cs 中: 第 112 行
   在 LCopy.App.Initialize() 在 Z:\Files\Git\Gitea\LCopy\LCopy\App.axaml.cs 中: 第 14 行
   在 Avalonia.AppBuilder.SetupUnsafe()
   在 Avalonia.AppBuilder.Setup()
   在 Avalonia.AppBuilder.SetupWithLifetime(IApplicationLifetime lifetime)
   在 Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder builder, String[] args, Action`1 lifetimeBuilder)
   在 LCopy.Program.Main(String[] args) 在 Z:\Files\Git\Gitea\LCopy\LCopy\Program.cs 中: 第 11 行

**Comment by Kir-Antipov** [comment]
Did you set `<PublishAot>true</PublishAot>` by any chance?

**Comment by Linlccc** [comment]
> Did you set `<PublishAot>true</PublishAot>` by any chance?

no

**Comment by Linlccc** [comment]
I have tried to start a new project, only using hotavalonia, but it still doesn't work, my csporj is as follows

```
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <BuiltInComInteropSupport>true</BuiltInComInteropSupport>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Models\" />
    <AvaloniaResource Include="Assets\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Avalonia" Version="11.2.2" />
    <PackageReference Include="Avalonia.Desktop" Version="11.2.2" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="11.2.2" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="11.2.2" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="Avalonia.Diagnostics" Version="11.2.2">
      <IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
      <PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
    </PackageReference>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.2.1" />
  </ItemGroup>

  <PropertyGroup Condition="'$(Configuration)' == 'Debug'">
    <!-- If you're a .vbproj user, replace ';' with ',' -->
    <DefineConstants>$(DefineConstants);ENABLE_XAML_HOT_RELOAD</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Condition="$(DefineConstants.Contains(ENABLE_XAML_HOT_RELOAD))" Include="Avalonia.Markup.Xaml.Loader" Version="11.2.2" />
    <PackageReference Condition="$(DefineConstants.Contains(ENABLE_XAML_HOT_RELOAD))" Include="HotAvalonia" Version="2.0.0" />
    <PackageReference Include="HotAvalonia.Extensions" Version="2.0.0" PrivateAssets="All" />
  </ItemGroup>
</Project>

```

**Comment by Kir-Antipov** [comment]
What's your OS and CPU arch?

**Comment by Discostoff** [comment]
I was not able to update to 2.0.0 via nugetpaket manager. i was only able to install one paket the otherone was resetting to the old version all the time. I changed the version in the project file by hand, that worked. In the output i got the error from the first post. at HotAvalonia.Helpers.MethodHelper.GetFunctionPointerAddress(MethodBase method)

**Comment by alexhelms** [comment]
I was able to update my project that originally created this issue to 2.0.0 and hot reload is now working again. I'm afraid I can't be of much help as to why others are having issues.

**Comment by Kir-Antipov** [comment]
> I was not able to update to 2.0.0 via nugetpaket manager. i was only able to install one paket the otherone was resetting to the old version all the time. I changed the version in the project file by hand, that worked.

The main `HotAvalonia` package is conditional, so your package manager might not handle it well. Manually specifying the dependency version is the recommended approach anyway.

> In the output i got the error from the first post. at HotAvalonia.Helpers.MethodHelper.GetFunctionPointerAddress(MethodBase method)

This code path should have been never reached, which suggests that you are operating in an unsupported environment. Therefore, I have the same questions for you:  
- Have you set `<PublishAot>true</PublishAot>` in your project configuration *(or anything else that disables `Ref.Emit`)*?  
- If not, what operating system and CPU architecture are you using?  

> I was able to update my project that originally created this issue to 2.0.0 and hot reload is now working again. I'm afraid I can't be of much help as to why others are having issues.

Yup, folks, the problem related to this issue has been resolved, so if you're still experiencing difficulties, it's better to open a new one instead of bumping an already resolved thread.

**Comment by Discostoff** [comment]
> > I was not able to update to 2.0.0 via nugetpaket manager. i was only able to install one paket the otherone was resetting to the old version all the time. I changed the version in the project file by hand, that worked.
> 
> The main `HotAvalonia` package is conditional, so your package manager might not handle it well. Manually specifying the dependency version is the recommended approach anyway.
> 
> > In the output i got the error from the first post. at HotAvalonia.Helpers.MethodHelper.GetFunctionPointerAddress(MethodBase method)
> 
> This code path should have been never reached, which suggests that you are operating in an unsupported environment. Therefore, I have the same questions for you:
> 
>     * Have you set `<PublishAot>true</PublishAot>` in your project configuration _(or anything else that disables `Ref.Emit`)_?
> 
>     * If not, what operating system and CPU architecture are you using?
> 
> 
> > I was able to update my project that originally created this issue to 2.0.0 and hot reload is now working again. I'm afraid I can't be of much help as to why others are having issues.
> 
> Yup, folks, the problem related to this issue has been fixed, so if you're still experiencing difficulties, it's better to open a new one instead of bumping an already resolved thread.

first time i heard about <PublishAot>true</PublishAot> so my answer is, no.
Windows 10 22H2 19045.5131 x64

**Comment by Kir-Antipov** [comment]
That definitely should not happen on x86-64 Windows. Please, open a new issue.

**Comment by Linlccc** [comment]
> What's your OS and CPU arch?

This issue occurs on both mac 15.1.1 (24B2091) and win11 arm64.

**Comment by Kir-Antipov** [comment]
See #17.
