### ISSUE TITLE
[Feature Request] Support for without xaml

### ISSUE THREAD

**Issue by DarkRRb** [Kir-Antipov/HotAvalonia#15]
```csharp
using Avalonia.Controls;

namespace AvaloniaDemo;

public class MainWindow : Window {
    public MainWindow() {
        Title = "Avalonia Demo";
        Content = new TabControl {
            ItemsSource = new TabItem[] {
                new TabItem() { Header = "Main", Content = new TextBlock { Text = "Main Content" } },
                new TabItem() { Header = "Configuration", Content = new TextBlock { Text = "Configuration Content" } },
            }
        };
    }
}
```

Is it possible to implement a hot restart when modifying the code here?

e.g.

```diff csharp
using Avalonia.Controls;

namespace AvaloniaDemo;

public class MainWindow : Window {
    public MainWindow() {
        Title = "Avalonia Demo";
        Content = new TabControl {
            ItemsSource = new TabItem[] {
                new TabItem() { Header = "Main", Content = new TextBlock { Text = "Main Content" } },
                new TabItem() { Header = "Configuration", Content = new TextBlock { Text = "Configuration Content" } },
+               new TabItem() { Header = "Hello", Content = new TextBlock { Text = "Hello Content" } }
            }
        };
    }
}
```

Probably a lot like #13.

**Comment by DarkRRb** [comment]
But hot reloading with `dotnet watch` alone doesn’t seem to update the interface in real time, maybe I’m missing something?

**Comment by Kir-Antipov** [comment]
Yeah, that's because it doesn't automatically re-run the code that has already been executed. For that, you can use a trick suggested by AVVI94.

**Comment by DarkRRb** [comment]
OK, I found MetadataUpdateHandlerAttribute when I was looking for information. Maybe I can simplify the operation with this attribute? But it may require more complicated processing

**Comment by Kir-Antipov** [comment]
You can use a metadata update handler for that instead of a crude "Rerender" button, for sure. Just trigger your UI rerender in the `UpdateApplication` method, there's no real need to actually process the updated types provided to it.

**Comment by DarkRRb** [comment]
OK, thanks for the help

**Comment by Kir-Antipov** [comment]
You are welcome!

I'll close this issue as "not planned", however, if anyone wants to contribute an `IHotReloadContext` for XAML-less controls to the project, I'm always open to PRs ;)
