### ISSUE TITLE
dotnet publish

### ISSUE THREAD

**Issue by Discostoff** [Kir-Antipov/HotAvalonia#19]
Hello,

i installed the new 2.0.0 version everything is working so far.
If i want to publish my app i get an error with the new version.
I use this command: dotnet publish ".\project.csproj" --nologo --force -p:PublishReadyToRun=true -p:PublishSingleFile=false --self-contained -p:IncludeNativeLibrariesForSelfExtract=true -c Release -o .\bin\Publish\Public

H:\Visual Studio\DRIVE\AvaloniaUI\IRacingApp.axaml.cs(5,7): error CS0246: The type or namespace name 'HotAvalonia'
 could not be found (are you missing a using directive or an assembly reference?) [H:\Visual Studio\DRIVE\Avalonia
UI\AvaloniaUI.csproj]

I tried just dotnet publish, same error.

PS H:\Visual Studio\DRIVE\IRDRIVE> dotnet publish .\IRDRIVE.csproj
Restore complete (0,9s)
  ACCSharedMemory succeeded (0,2s) → H:\Visual Studio\DRIVE\ACCSharedMemory\bin\Release\net6.0\ACCSharedMemory.dll
  Models succeeded (0,3s) → H:\Visual Studio\DRIVE\Models\bin\Release\net9.0-windows7.0\Models.dll
  IRacing.Data succeeded (0,3s) → H:\Visual Studio\DRIVE\IRacing.Data\bin\Release\net9.0-windows\IRacing.Data.dll
  ACC.Data succeeded (0,3s) → H:\Visual Studio\DRIVE\ACC.Data\bin\Release\net9.0-windows\ACC.Data.dll
  ViewModels succeeded (0,3s) → H:\Visual Studio\DRIVE\ViewModels\bin\Release\net9.0-windows\ViewModels.dll
  AvaloniaUI failed with 1 error(s) (0,5s)
    C:\Users\jorgo\.nuget\packages\hotavalonia.extensions\2.0.0\contentFiles\cs\any\AvaloniaHotReloadExtensions.cs(179,66): error CS0246: The type or namespace name 'Func<,>' could not be found (are you missing a using directive or an assembly reference?)
    
I created a new test app, same error.
https://github.com/Discostoff/AvaloniaDotNetPublish

**Comment by Kir-Antipov** [comment]
Hi! Should be fixed in `v2.0.1` :)

**Comment by Discostoff** [comment]
Thank you
