### ISSUE TITLE
Internal control in sample causes hot reload to fail

### ISSUE THREAD

**Issue by stevemonaco** [Kir-Antipov/HotAvalonia#22]
Regression from https://github.com/Kir-Antipov/HotAvalonia/commit/207e2498b79d11628697a2996b6c07c4879bf53f

![hotreloadfail](https://github.com/user-attachments/assets/c07ab610-60d2-4879-b3cd-1bada7e92cc2)

Works locally once I change it back to `public`.

Local environment: Windows 11 23H2. VS 17.12.0.

Raising issue on behalf of a new user.

**Comment by Kir-Antipov** [comment]
It shouldn't. Could you, please, share you debug log?

**Comment by stevemonaco** [comment]
Certainly.

[hotreloadfail.txt](https://github.com/user-attachments/files/18117426/hotreloadfail.txt)

Avalonia's XAML editor seems to have some complaints about it being `internal` too, though it's a ghost error as the project builds+runs fine on its own.

![image](https://github.com/user-attachments/assets/605c7114-9a71-4952-8a3a-7df3aac537b3)

**Comment by Kir-Antipov** [comment]
Right, that's why I hadn't noticed this problem myself - if you reload `ToDoItemControl` first and **then** reload `ToDoListView`, it works 😅
