### ISSUE TITLE
XAML-Theme @Kir-Antipov

### ISSUE THREAD

**Issue by PhilWeisz** [Kir-Antipov/HotAvalonia#6]
xd :P  I'd only like to know which theme you're using for these nice colors in XAML 

![image](https://github.com/Kir-Antipov/HotAvalonia/assets/122535935/2cff3641-8107-45a5-ae93-c84733f786b9)

**Comment by Kir-Antipov** [comment]
Hi! This isn't just a XAML-only theme; it's actually quite nice to use for general coding as well.

It's a Visual Studio Code theme called "Ardent." You can find it here: https://marketplace.visualstudio.com/items?itemName=alexanderte.ardent-vscode. It offers 36 variations, so you can choose the one that's most pleasant and/or easiest on your eyes. Personally, I prefer the "contrast 0, chroma 1, lightness 1" variant. It's one of the most pleasing dark themes I've come across, and it's a shame that it has only been downloaded 3.5k times!

However, there's one slight issue with it - the color token for comments is misconfigured, causing them to appear white. To fix this, I recommend adding the following block to your VSC's `settings.json`:

```json
"editor.tokenColorCustomizations": {
    "[Ardent (contrast 0, chroma 1, lightness 1)]": {
        "textMateRules": [
            {
                "scope": [
                    "comment",
                    "punctuation.definition.comment.js"
                ],
                "settings": {
                    "foreground": "#6272a4"
                }
            }
        ]
    }
},
```

Unfortunately, the author seems to have disappeared from the internet, and their GitHub profile is also gone, leaving no way to submit a fix.

Hope that answers the question :)
